// Custom shader file for Metro-b1-2.bsp
// Generated by Q3Map2 (ydnar)
// Do not edit! This file is overwritten on recompiles.

Metro-b1-2/9033651CF28AD2575822918198C81A1A
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro-b1-2/lm_0014.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/Metro-b1-2/lm_0014.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 -0.50000
	}
	{
		map maps/Metro-b1-2/lm_0014.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 -0.50000
	}

	{
		map textures/metro/pub/auchan_achete.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-2/05025E28FCBC2B12D3057C30D078DA9A
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro-b1-2/lm_0014.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}
	{
		map maps/Metro-b1-2/lm_0014.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.00000
	}

	{
		map textures/metro/pub/logo_sego.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-2/158558FC06FC3AAAC5D72E9E5872FE12
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro-b1-2/lm_0014.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/Metro-b1-2/lm_0014.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.50000 0.00000
	}
	{
		map maps/Metro-b1-2/lm_0014.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.50000 0.50000
	}

	{
		map textures/metro/pub/frtel.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-2/7D10097A5B3694EFD39E25910A3CB6F1
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro-b1-2/lm_0014.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/Metro-b1-2/lm_0014.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.50000 0.00000
	}
	{
		map maps/Metro-b1-2/lm_0014.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.50000 0.50000
	}

	{
		map textures/metro/pub/sncf.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-2/06162D5EB06F5673C53C342DC8562B68
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro-b1-2/lm_0012.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/Metro-b1-2/lm_0013.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
	}
	{
		map maps/Metro-b1-2/lm_0012.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.50000 0.00000
	}

	{
		map textures/metro/marble50b.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-2/93C2B40F4FDE4C2E38A2F76D7464D74F
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro-b1-2/lm_0003.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}
	{
		map maps/Metro-b1-2/lm_0003.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}

	{
		map textures/metro/KOsAD_MarcheFace.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-2/8C37E11196D3B8E5FE7BD0A6910D08C0
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro-b1-2/lm_0003.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.00000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}

	{
		map textures/metro/KOsAD_MarcheFace.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-2/8C329FC7F0D93D43033483E524BF478D
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro-b1-2/lm_0003.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.50000 0.50000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}

	{
		map textures/metro/KOsAD_MarcheFace.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-2/4AEB229BD1B625CCAD8F27C6B359FAD7
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro-b1-2/lm_0005.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 -0.50000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.19531 0.00000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.19531 0.00781
	}

	{
		map textures/metro/KOsAD_MarcheTop2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-2/2AA6056E91DB450649C2160FE69F5DFE
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro-b1-2/lm_0005.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}
	{
		map maps/Metro-b1-2/lm_0005.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.50000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50781 0.00000
	}

	{
		map textures/metro/KOsAD_MarcheTop2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-2/96B655F8D0160DE066B5C39386A22517
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50781 0.00000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.01563 0.03125
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50781 0.03125
	}

	{
		map textures/metro/KOsAD_MarcheTop2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-2/D0FB25214503C75A7A698C986949A983
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro-b1-2/lm_0005.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.49219 0.03125
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.03125
	}

	{
		map textures/metro/KOsAD_MarcheTop2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-2/C9A2D0460EF238BFC25F0C40D1EEE7E7
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.50000
	}
	{
		map maps/Metro-b1-2/lm_0005.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}

	{
		map textures/metro/KOsAD_MarcheTop2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-2/AD2B81DBCD521A3ADB5B604BEB71975D
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro-b1-2/lm_0004.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/Metro-b1-2/lm_0005.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.00000
	}

	{
		map textures/metro/KOsAD_MarcheTop2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-2/A74E48ED1BAA4EF6D856B6ED7D39B682
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro-b1-2/lm_0005.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/Metro-b1-2/lm_0005.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.50000 0.00000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.03125
	}

	{
		map textures/metro/KOsAD_MarcheTop2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-2/871D61B5D24649C179296724A7924BF8
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro-b1-2/lm_0005.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/Metro-b1-2/lm_0005.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 -0.50000
	}
	{
		map maps/Metro-b1-2/lm_0005.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.00000
	}

	{
		map textures/metro/KOsAD_MarcheTop2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-2/71542F3736871C72960E1C19E8DF3B82
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.50000
	}
	{
		map maps/Metro-b1-2/lm_0005.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}
	{
		map maps/Metro-b1-2/lm_0005.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.50000
	}

	{
		map textures/metro/KOsAD_MarcheTop2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-2/E8C047AF0D9289520307597AA5E218E5
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.00000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.50000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.03125
	}

	{
		map textures/metro/KOsAD_MarcheTop2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-2/F47970E5826F41C64558801AADDFF3ED
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.00000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.50000
	}

	{
		map textures/metro/KOsAD_MarcheTop2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-2/349C8D90066BDFF728FEC647A01E5000
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro-b1-2/lm_0005.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/Metro-b1-2/lm_0005.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.00000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.19531 0.00781
	}

	{
		map textures/metro/KOsAD_MarcheTop2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-2/7E961D32C016C012F454326D34EFE2A5
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro-b1-2/lm_0015.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/Metro-b1-2/lm_0016.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}

	{
		map textures/metro/sttp13-Extincteur3.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-2/A3D6B39F421861B5C5E8A73E378956DC
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro-b1-2/lm_0008.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/Metro-b1-2/lm_0005.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.50000 -0.50000
	}
	{
		map maps/Metro-b1-2/lm_0006.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.50000 -0.50000
	}

	{
		map textures/metro/KOsAD_MetalLampe.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-2/C982FA170AADC02E54E72A14E1CA3CE3
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro-b1-2/lm_0005.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/Metro-b1-2/lm_0008.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
	}
	{
		map maps/Metro-b1-2/lm_0009.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
	}

	{
		map textures/metro/KOsAD_MetalLampe.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-2/359DA5238458526B65EBF38A0E305752
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro-b1-2/lm_0006.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/Metro-b1-2/lm_0009.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
	}
	{
		map maps/Metro-b1-2/lm_0005.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 -0.50000
	}

	{
		map textures/metro/KOsAD_MetalLampe.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-2/E67AD10913FB4EE70A00D3F7554E4E91
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro-b1-2/lm_0006.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/Metro-b1-2/lm_0008.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
	}
	{
		map maps/Metro-b1-2/lm_0009.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
	}

	{
		map textures/metro/KOsAD_MetalLampe.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-2/498C69B8BCC303AC72EABD6642E208CC
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro-b1-2/lm_0005.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/Metro-b1-2/lm_0006.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
	}
	{
		map maps/Metro-b1-2/lm_0007.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
	}

	{
		map textures/metro/KOsAD_MetalLampe.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-2/5C87D7AAD076EF44AB2FACB7C2A0051F
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro-b1-2/lm_0005.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/Metro-b1-2/lm_0006.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
	}
	{
		map maps/Metro-b1-2/lm_0008.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
	}

	{
		map textures/metro/KOsAD_MetalLampe.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-2/6BDF9905BFAF7BC79602971B7459D3FF
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro-b1-2/lm_0006.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/Metro-b1-2/lm_0007.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
	}
	{
		map maps/Metro-b1-2/lm_0008.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
	}

	{
		map textures/metro/KOsAD_MetalLampe.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-2/F6BA59A34A317E0788992BCCC9B26E97
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.00000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.01563 0.00000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.03125 0.00000
	}

	{
		map textures/metro/KOsAD_MetalLampe.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-2/347776D67A7651661ACED82517E49EFE
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro-b1-2/lm_0009.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.16406 0.00000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.05469
	}

	{
		map textures/metro/KOsAD_MetalLampe.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-2/CE7BDAB3582C70B57932037BA531A8F9
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro-b1-2/lm_0009.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/Metro-b1-2/lm_0009.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 -0.50000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.05469
	}

	{
		map textures/metro/KOsAD_MetalLampe.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-2/A45B5ACB9F24B6DBED969AD61FD1A0EE
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.00000
	}
	{
		map maps/Metro-b1-2/lm_0009.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.00000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.01563 0.00000
	}

	{
		map textures/metro/KOsAD_MetalLampe.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-2/CB6EB134F759BB52B9EA6249320D0404
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro-b1-2/lm_0008.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/Metro-b1-2/lm_0009.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
	}
	{
		map maps/Metro-b1-2/lm_0005.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 -0.50000
	}

	{
		map textures/metro/KOsAD_MetalLampe.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-2/CD3F29239D65EC841770FA7D66EC8647
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro-b1-2/lm_0005.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/Metro-b1-2/lm_0007.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
	}
	{
		map maps/Metro-b1-2/lm_0008.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
	}

	{
		map textures/metro/KOsAD_MetalLampe.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-2/26D639BB7140F381E080BF36CB993A38
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro-b1-2/lm_0006.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/Metro-b1-2/lm_0007.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
	}
	{
		map maps/Metro-b1-2/lm_0009.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
	}

	{
		map textures/metro/KOsAD_MetalLampe.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-2/270A17533A1BDD4204F6043D26EE3269
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro-b1-2/lm_0008.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/Metro-b1-2/lm_0005.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 -0.50000
	}
	{
		map maps/Metro-b1-2/lm_0005.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.00000
	}

	{
		map textures/metro/KOsAD_MetalLampe.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-2/9AE4835B5A209F4ACA13ED6ACB90D815
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro-b1-2/lm_0007.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/Metro-b1-2/lm_0008.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
	}
	{
		map maps/Metro-b1-2/lm_0009.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
	}

	{
		map textures/metro/KOsAD_MetalLampe.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-2/E1921778E5124B49B6DFDA61DF2EA635
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro-b1-2/lm_0001.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/Metro-b1-2/lm_0001.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 -0.50000
	}
	{
		map maps/Metro-b1-2/lm_0001.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.50000 0.00000
	}

	{
		map textures/metro/Alumb_t.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-2/2B1984B395E5A4399C557693CF616D11
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro-b1-2/lm_0001.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.00000
	}
	{
		map maps/Metro-b1-2/lm_0001.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 -0.50000
	}

	{
		map textures/metro/Alumb_t.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-2/9E03F1D56824C0292D9CCA6022AAAA5C
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.12500
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.25000
	}

	{
		map textures/metro/navily-ns_bleu.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-2/66371673AE0CD690398F728FBA39CB21
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.11719
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.23438
	}

	{
		map textures/metro/navily-ns_bleu.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-2/119D8941621210025F55A746A40A7B3A
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.11719
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.23437
	}

	{
		map textures/metro/navily-ns_bleu.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-2/B522C1B74D5F88C302DF769BBB261EFF
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.12500
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.25000
	}

	{
		map textures/metro/RFSP-STEX5b.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-2/2F496655C5C341BAEF028E5E3B5513B7
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.11719
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.23438
	}

	{
		map textures/metro/RFSP-STEX5b.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

