// Custom shader file for Metro-b1-1.bsp
// Generated by Q3Map2 (ydnar)
// Do not edit! This file is overwritten on recompiles.

Metro-b1-1/60D2D29EB4A1C2ECF193CEB7484C01FC
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro-b1-1/lm_0016.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/Metro-b1-1/lm_0015.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.50000 0.00000
	}
	{
		map maps/Metro-b1-1/lm_0016.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 -0.50000
	}

	{
		map textures/metro/pub/auchan_achete.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-1/D0571EA4D48DD1C4BDB1FB0480B1D1D1
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro-b1-1/lm_0016.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 -0.50000
	}
	{
		map maps/Metro-b1-1/lm_0016.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.00000
	}
	{
		map maps/Metro-b1-1/lm_0015.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.44531 -0.55469
	}

	{
		map textures/metro/pub/logo_sego.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-1/09B2359E78FA63301181A93DEEE8E1D7
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro-b1-1/lm_0016.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/Metro-b1-1/lm_0015.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 -0.50000
	}
	{
		map maps/Metro-b1-1/lm_0015.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 -0.85156
	}

	{
		map textures/metro/pub/frtel.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-1/4E699AC0E67DFF5A65679AA0BA289280
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.60156 0.00000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.79688 0.00000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.80469 0.10156
	}

	{
		map textures/metro/pub/sncf.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-1/E6ECE7AAD480830F7674A42E32BAA47D
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro-b1-1/lm_0015.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.28906 0.00000
	}
	{
		map maps/Metro-b1-1/lm_0015.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.31250 0.00000
	}

	{
		map textures/metro/marble50b.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-1/302959BDD1742C48B8EA79F18B54E514
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.00000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.50000
	}

	{
		map textures/metro/KOsAD_MarcheFace.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-1/49B64B08009B62DC289EE874DDECD757
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro-b1-1/lm_0004.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.50000 0.50000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}

	{
		map textures/metro/KOsAD_MarcheFace.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-1/8598197F83F8BE6E88478A52625E73D4
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro-b1-1/lm_0004.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}
	{
		map maps/Metro-b1-1/lm_0004.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}

	{
		map textures/metro/KOsAD_MarcheFace.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-1/F2ECE33F50071A5C3BC691A8E69ADF83
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro-b1-1/lm_0006.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/Metro-b1-1/lm_0006.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.50000 0.00000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.39063 0.01563
	}

	{
		map textures/metro/KOsAD_MarcheTop2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-1/BCF220BE6DC05020DA1BFF4EE56BDCB2
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.00000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.03125
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.49219 0.03125
	}

	{
		map textures/metro/KOsAD_MarcheTop2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-1/F47970E5826F41C64558801AADDFF3ED
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.00000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.50000
	}

	{
		map textures/metro/KOsAD_MarcheTop2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-1/1991797A5C5D3BAE4C950C44AA9A4AC0
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro-b1-1/lm_0006.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/Metro-b1-1/lm_0006.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.50000 0.00000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.03125
	}

	{
		map textures/metro/KOsAD_MarcheTop2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-1/D961737EF2556C68ABD8B032568425AD
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.00000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.19531 0.06250
	}
	{
		map maps/Metro-b1-1/lm_0006.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.12500 -0.88281
	}

	{
		map textures/metro/KOsAD_MarcheTop2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-1/5A28266D7D4EBD2380AD38F71E34F9B2
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro-b1-1/lm_0006.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/Metro-b1-1/lm_0006.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.50000 0.00000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.49219 0.06250
	}

	{
		map textures/metro/KOsAD_MarcheTop2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-1/EE8012EF68E6A31D7B16E14406E18DA6
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.50000
	}
	{
		map maps/Metro-b1-1/lm_0006.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.00000
	}

	{
		map textures/metro/KOsAD_MarcheTop2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-1/A342717E8E44CFC70B27B0B8550A17D3
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.00000
	}
	{
		map maps/Metro-b1-1/lm_0006.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.00000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.03125
	}

	{
		map textures/metro/KOsAD_MarcheTop2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-1/29768B8318213DEDBF109D083B454E8E
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro-b1-1/lm_0006.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.50000 0.50000
	}
	{
		map maps/Metro-b1-1/lm_0006.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.53906 0.03125
	}

	{
		map textures/metro/KOsAD_MarcheTop2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-1/76E1288905B521832E44551564A353CE
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro-b1-1/lm_0006.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}
	{
		map maps/Metro-b1-1/lm_0006.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.50000 0.50000
	}

	{
		map textures/metro/KOsAD_MarcheTop2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-1/574F981362EB04AC70669605338A7042
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro-b1-1/lm_0006.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}
	{
		map maps/Metro-b1-1/lm_0006.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.50000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50781 0.00000
	}

	{
		map textures/metro/KOsAD_MarcheTop2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-1/181013FF98F4D941E71BB6583F4A9988
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro-b1-1/lm_0017.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/Metro-b1-1/lm_0018.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
	}
	{
		map maps/Metro-b1-1/lm_0018.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.50000 -0.50000
	}

	{
		map textures/metro/sttp13-Extincteur3.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-1/A1E94D7EFD27D4A754232B63521469C3
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro-b1-1/lm_0006.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/Metro-b1-1/lm_0007.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.00000
	}
	{
		map maps/Metro-b1-1/lm_0007.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}

	{
		map textures/metro/KOsAD_MetalLampe.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-1/025C3D0952CD0D4A4AFCA1574F2DE8C9
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro-b1-1/lm_0008.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.40625 0.28125
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.23438 0.39844
	}

	{
		map textures/metro/KOsAD_MetalLampe.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-1/2F75D08C168D93B6308EEC5A1C13C723
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro-b1-1/lm_0007.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/Metro-b1-1/lm_0006.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 -0.50000
	}
	{
		map maps/Metro-b1-1/lm_0007.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 -0.50000
	}

	{
		map textures/metro/KOsAD_MetalLampe.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-1/F2A1D199E1BA90A8B470E7FACDF34F06
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro-b1-1/lm_0006.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/Metro-b1-1/lm_0008.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
	}
	{
		map maps/Metro-b1-1/lm_0009.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
	}

	{
		map textures/metro/KOsAD_MetalLampe.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-1/7C450D54F46C1AA30F8969180D991D6B
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro-b1-1/lm_0007.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/Metro-b1-1/lm_0008.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
	}
	{
		map maps/Metro-b1-1/lm_0009.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
	}

	{
		map textures/metro/KOsAD_MetalLampe.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-1/F59EB26AB8D35442C830CCC0C62DE3C2
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro-b1-1/lm_0006.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/Metro-b1-1/lm_0009.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
	}
	{
		map maps/Metro-b1-1/lm_0010.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
	}

	{
		map textures/metro/KOsAD_MetalLampe.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-1/88E06B1C4AED7516FF9B09B30408A0D5
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro-b1-1/lm_0008.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/Metro-b1-1/lm_0009.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
	}
	{
		map maps/Metro-b1-1/lm_0010.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
	}

	{
		map textures/metro/KOsAD_MetalLampe.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-1/C91694C4D857E6C5EC2EF9D4E0717C98
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro-b1-1/lm_0010.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.01563 0.00000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.03125 0.00000
	}

	{
		map textures/metro/KOsAD_MetalLampe.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-1/9704D506AA408FA5891BDE1EF9D9C284
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro-b1-1/lm_0010.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}
	{
		map maps/Metro-b1-1/lm_0010.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}

	{
		map textures/metro/KOsAD_MetalLampe.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-1/39DFF5507A833E0BE9B6ED74446003EB
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro-b1-1/lm_0006.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/Metro-b1-1/lm_0007.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.00000
	}
	{
		map maps/Metro-b1-1/lm_0007.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.50000
	}

	{
		map textures/metro/KOsAD_MetalLampe.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-1/D6A382A1656CCBCB071DCE8D341BB015
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro-b1-1/lm_0006.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.50000 0.00000
	}
	{
		map maps/Metro-b1-1/lm_0006.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.50000 0.50000
	}
	{
		map maps/Metro-b1-1/lm_0006.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}

	{
		map textures/metro/KOsAD_MetalLampe.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-1/F03102DE0B164FDBFBD5BD0D4CCCAF51
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro-b1-1/lm_0001.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.02344 0.00000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.06250 0.00000
	}

	{
		map textures/metro/Alumb_t.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-1/1C92D548B744725FFC718ABE5FD3C1D2
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.00000
	}
	{
		map maps/Metro-b1-1/lm_0001.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 -0.50000
	}
	{
		map maps/Metro-b1-1/lm_0001.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.00000
	}

	{
		map textures/metro/Alumb_t.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-1/49BDF8EA089747882355C1A76351E71C
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.67969 0.20313
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.65625 0.20313
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.63281 0.20313
	}

	{
		map textures/metro/Alumb_t.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-1/5C6C935ABFFCD218A2C02F4C51AF8996
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro-b1-1/lm_0001.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.04688 0.00000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.07031 0.00000
	}

	{
		map textures/metro/Alumb_t.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-1/1A7FB7F9F4C6B2C94ECC14F0ABDBE7D8
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro-b1-1/lm_0001.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 -0.50000
	}
	{
		map maps/Metro-b1-1/lm_0001.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.00000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.02344 0.00000
	}

	{
		map textures/metro/Alumb_t.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-1/2F06331A0A4DDEBDD6DD6F8A8EEE86F2
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro-b1-1/lm_0001.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.02344 0.00000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.04688 0.00000
	}

	{
		map textures/metro/Alumb_t.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-1/DF902FB7C49B54A4B04C35F5D269D97B
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro-b1-1/lm_0001.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/Metro-b1-1/lm_0001.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 -0.50000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.02344 0.00000
	}

	{
		map textures/metro/Alumb_t.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-1/5B60DDA2A17E00DF5A42C86A9A9FE0B8
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro-b1-1/lm_0001.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.13281 0.00000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.57813 0.20313
	}

	{
		map textures/metro/Alumb_t.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-1/B7A47CACF6D5857733F388B2FC19902C
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro-b1-1/lm_0001.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/Metro-b1-1/lm_0001.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 -0.50000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.96875 0.04688
	}

	{
		map textures/metro/Alumb_t.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-1/9032124D5E6F73FB493EFF0E032FFB7A
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.12500
	}
	{
		map maps/Metro-b1-1/lm_0012.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
	}
	{
		map maps/Metro-b1-1/lm_0013.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
	}

	{
		map textures/metro/navily-ns_bleu.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-1/A8B1A68533F54FB56D2FDCB1C1B94132
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro-b1-1/lm_0011.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/Metro-b1-1/lm_0011.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 -0.50000
	}
	{
		map maps/Metro-b1-1/lm_0011.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 -0.67969
	}

	{
		map textures/metro/navily-ns_bleu.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-1/7ACF25F268639A4834B6D312826BFE08
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.12500
	}
	{
		map maps/Metro-b1-1/lm_0012.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
	}
	{
		map maps/Metro-b1-1/lm_0013.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
	}

	{
		map textures/metro/RFSP-STEX5b.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro-b1-1/DB1759F264BE7B3327EE9A77EBF0DC5B
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro-b1-1/lm_0011.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/Metro-b1-1/lm_0011.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 -0.50000
	}
	{
		map maps/Metro-b1-1/lm_0011.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 -0.67969
	}

	{
		map textures/metro/RFSP-STEX5b.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

