// Custom shader file for Metro-b1-2.bsp
// Generated by Q3Map2 (ydnar)
// Do not edit! This file is overwritten on recompiles.

metro/9033651cf28ad2575822918198c81a1a
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3map2_metro/lm_0014
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/q3map2_metro/lm_0014
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 -0.50000
	}
	{
		map maps/q3map2_metro/lm_0014
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 -0.50000
	}

	{
		map textures/metro/pub/auchan_achete
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

metro/05025e28fcbc2b12d3057c30d078da9a
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3map2_metro/lm_0014
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}
	{
		map maps/q3map2_metro/lm_0014
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.00000
	}

	{
		map textures/metro/pub/logo_sego
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

metro/158558fc06fc3aaac5d72e9e5872fe12
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3map2_metro/lm_0014
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/q3map2_metro/lm_0014
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.50000 0.00000
	}
	{
		map maps/q3map2_metro/lm_0014
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.50000 0.50000
	}

	{
		map textures/metro/pub/frtel
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

metro/7d10097a5b3694efd39e25910a3cb6f1
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3map2_metro/lm_0014
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/q3map2_metro/lm_0014
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.50000 0.00000
	}
	{
		map maps/q3map2_metro/lm_0014
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.50000 0.50000
	}

	{
		map textures/metro/pub/sncf
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

metro/06162d5eb06f5673c53c342dc8562b68
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3map2_metro/lm_0012
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/q3map2_metro/lm_0013
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
	}
	{
		map maps/q3map2_metro/lm_0012
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.50000 0.00000
	}

	{
		map textures/metro/marble50b
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

metro/93c2b40f4fde4c2e38a2f76d7464d74f
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3map2_metro/lm_0003
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}
	{
		map maps/q3map2_metro/lm_0003
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}

	{
		map textures/metro/kosad_marcheface
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

metro/8c37e11196d3b8e5fe7bd0a6910d08c0
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3map2_metro/lm_0003
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.00000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}

	{
		map textures/metro/kosad_marcheface
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

metro/8c329fc7f0d93d43033483e524bf478d
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3map2_metro/lm_0003
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.50000 0.50000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}

	{
		map textures/metro/kosad_marcheface
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

metro/4aeb229bd1b625ccad8f27c6b359fad7
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3map2_metro/lm_0005
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 -0.50000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.19531 0.00000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.19531 0.00781
	}

	{
		map textures/metro/kosad_marchetop2
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

metro/2aa6056e91db450649c2160fe69f5dfe
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3map2_metro/lm_0005
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}
	{
		map maps/q3map2_metro/lm_0005
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.50000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50781 0.00000
	}

	{
		map textures/metro/kosad_marchetop2
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

metro/96b655f8d0160de066b5c39386a22517
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50781 0.00000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.01563 0.03125
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50781 0.03125
	}

	{
		map textures/metro/kosad_marchetop2
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

metro/d0fb25214503c75a7a698c986949a983
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3map2_metro/lm_0005
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.49219 0.03125
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.03125
	}

	{
		map textures/metro/kosad_marchetop2
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

metro/c9a2d0460ef238bfc25f0c40d1eee7e7
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.50000
	}
	{
		map maps/q3map2_metro/lm_0005
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}

	{
		map textures/metro/kosad_marchetop2
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

metro/ad2b81dbcd521a3adb5b604beb71975d
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3map2_metro/lm_0004
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/q3map2_metro/lm_0005
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.00000
	}

	{
		map textures/metro/kosad_marchetop2
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

metro/a74e48ed1baa4ef6d856b6ed7d39b682
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3map2_metro/lm_0005
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/q3map2_metro/lm_0005
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.50000 0.00000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.03125
	}

	{
		map textures/metro/kosad_marchetop2
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

metro/871d61b5d24649c179296724a7924bf8
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3map2_metro/lm_0005
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/q3map2_metro/lm_0005
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 -0.50000
	}
	{
		map maps/q3map2_metro/lm_0005
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.00000
	}

	{
		map textures/metro/kosad_marchetop2
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

metro/71542f3736871c72960e1c19e8df3b82
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.50000
	}
	{
		map maps/q3map2_metro/lm_0005
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}
	{
		map maps/q3map2_metro/lm_0005
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.50000
	}

	{
		map textures/metro/kosad_marchetop2
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

metro/e8c047af0d9289520307597aa5e218e5
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.00000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.50000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.03125
	}

	{
		map textures/metro/kosad_marchetop2
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

metro/f47970e5826f41c64558801aaddff3ed
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.00000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.50000
	}

	{
		map textures/metro/kosad_marchetop2
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

metro/349c8d90066bdff728fec647a01e5000
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3map2_metro/lm_0005
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/q3map2_metro/lm_0005
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.00000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.19531 0.00781
	}

	{
		map textures/metro/kosad_marchetop2
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

metro/7e961d32c016c012f454326d34efe2a5
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3map2_metro/lm_0015
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/q3map2_metro/lm_0016
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}

	{
		map textures/metro/sttp13-extincteur3
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

metro/a3d6b39f421861b5c5e8a73e378956dc
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3map2_metro/lm_0008
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/q3map2_metro/lm_0005
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.50000 -0.50000
	}
	{
		map maps/q3map2_metro/lm_0006
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.50000 -0.50000
	}

	{
		map textures/metro/kosad_metallampe
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

metro/c982fa170aadc02e54e72a14e1ca3ce3
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3map2_metro/lm_0005
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/q3map2_metro/lm_0008
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
	}
	{
		map maps/q3map2_metro/lm_0009
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
	}

	{
		map textures/metro/kosad_metallampe
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

metro/359da5238458526b65ebf38a0e305752
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3map2_metro/lm_0006
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/q3map2_metro/lm_0009
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
	}
	{
		map maps/q3map2_metro/lm_0005
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 -0.50000
	}

	{
		map textures/metro/kosad_metallampe
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

metro/e67ad10913fb4ee70a00d3f7554e4e91
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3map2_metro/lm_0006
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/q3map2_metro/lm_0008
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
	}
	{
		map maps/q3map2_metro/lm_0009
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
	}

	{
		map textures/metro/kosad_metallampe
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

metro/498c69b8bcc303ac72eabd6642e208cc
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3map2_metro/lm_0005
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/q3map2_metro/lm_0006
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
	}
	{
		map maps/q3map2_metro/lm_0007
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
	}

	{
		map textures/metro/kosad_metallampe
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

metro/5c87d7aad076ef44ab2facb7c2a0051f
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3map2_metro/lm_0005
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/q3map2_metro/lm_0006
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
	}
	{
		map maps/q3map2_metro/lm_0008
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
	}

	{
		map textures/metro/kosad_metallampe
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

metro/6bdf9905bfaf7bc79602971b7459d3ff
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3map2_metro/lm_0006
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/q3map2_metro/lm_0007
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
	}
	{
		map maps/q3map2_metro/lm_0008
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
	}

	{
		map textures/metro/kosad_metallampe
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

metro/f6ba59a34a317e0788992bccc9b26e97
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.00000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.01563 0.00000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.03125 0.00000
	}

	{
		map textures/metro/kosad_metallampe
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

metro/347776d67a7651661aced82517e49efe
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3map2_metro/lm_0009
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.16406 0.00000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.05469
	}

	{
		map textures/metro/kosad_metallampe
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

metro/ce7bdab3582c70b57932037ba531a8f9
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3map2_metro/lm_0009
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/q3map2_metro/lm_0009
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 -0.50000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.05469
	}

	{
		map textures/metro/kosad_metallampe
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

metro/a45b5acb9f24b6dbed969ad61fd1a0ee
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.00000
	}
	{
		map maps/q3map2_metro/lm_0009
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.00000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.01563 0.00000
	}

	{
		map textures/metro/kosad_metallampe
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

metro/cb6eb134f759bb52b9ea6249320d0404
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3map2_metro/lm_0008
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/q3map2_metro/lm_0009
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
	}
	{
		map maps/q3map2_metro/lm_0005
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 -0.50000
	}

	{
		map textures/metro/kosad_metallampe
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

metro/cd3f29239d65ec841770fa7d66ec8647
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3map2_metro/lm_0005
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/q3map2_metro/lm_0007
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
	}
	{
		map maps/q3map2_metro/lm_0008
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
	}

	{
		map textures/metro/kosad_metallampe
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

metro/26d639bb7140f381e080bf36cb993a38
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3map2_metro/lm_0006
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/q3map2_metro/lm_0007
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
	}
	{
		map maps/q3map2_metro/lm_0009
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
	}

	{
		map textures/metro/kosad_metallampe
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

metro/270a17533a1bdd4204f6043d26ee3269
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3map2_metro/lm_0008
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/q3map2_metro/lm_0005
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 -0.50000
	}
	{
		map maps/q3map2_metro/lm_0005
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.00000
	}

	{
		map textures/metro/kosad_metallampe
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

metro/9ae4835b5a209f4aca13ed6acb90d815
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3map2_metro/lm_0007
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/q3map2_metro/lm_0008
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
	}
	{
		map maps/q3map2_metro/lm_0009
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
	}

	{
		map textures/metro/kosad_metallampe
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

metro/e1921778e5124b49b6dfda61df2ea635
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3map2_metro/lm_0001
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/q3map2_metro/lm_0001
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 -0.50000
	}
	{
		map maps/q3map2_metro/lm_0001
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.50000 0.00000
	}

	{
		map textures/metro/alumb_t
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

metro/2b1984b395e5a4399c557693cf616d11
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3map2_metro/lm_0001
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.00000
	}
	{
		map maps/q3map2_metro/lm_0001
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 -0.50000
	}

	{
		map textures/metro/alumb_t
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

metro/9e03f1d56824c0292d9cca6022aaaa5c
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.12500
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.25000
	}

	{
		map textures/metro/navily-ns_bleu
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

metro/66371673ae0cd690398f728fba39cb21
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.11719
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.23438
	}

	{
		map textures/metro/navily-ns_bleu
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

metro/119d8941621210025f55a746a40a7b3a
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.11719
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.23437
	}

	{
		map textures/metro/navily-ns_bleu
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

metro/b522c1b74d5f88c302df769bbb261eff
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.12500
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.25000
	}

	{
		map textures/metro/rfsp-stex5b
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

metro/2f496655c5c341baef028e5e3b5513b7
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.11719
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.23438
	}

	{
		map textures/metro/rfsp-stex5b
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

