// Custom shader file for Metro.bsp
// Generated by Q3Map2 (ydnar)
// Do not edit! This file is overwritten on recompiles.

Metro/452F368C7E654961BBA9CE6ECA273D31
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro/lm_0014.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/Metro/lm_0016.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
	}
	{
		map maps/Metro/lm_0013.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.50000 -0.50000
	}

	{
		map textures/metro/pub/auchan_achete.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro/917E4B9224DE68E9DC96B26280230A94
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro/lm_0016.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.00000
	}
	{
		map maps/Metro/lm_0016.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.50000
	}
	{
		map maps/Metro/lm_0014.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.35938 0.47656
	}

	{
		map textures/metro/pub/logo_sego.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro/F87AE4B34D78113584B9E4D7CCDA068B
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro/lm_0013.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.48438 -0.42969
	}
	{
		map maps/Metro/lm_0014.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.11719 0.03125
	}
	{
		map maps/Metro/lm_0015.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.10156 -0.85156
	}

	{
		map textures/metro/pub/frtel.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro/7F22092CCFF0D43CD05E4569F271ED8F
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.19531 0.00000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.19531 0.10156
	}

	{
		map textures/metro/pub/sncf.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro/E43D1A062F773E9410545D2A2AAED5E8
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro/lm_0014.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.28906 0.00000
	}
	{
		map maps/Metro/lm_0014.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.31250 0.00000
	}

	{
		map textures/metro/marble50b.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro/BE6CD90FC91815956DD12C0D4187A4F9
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro/lm_0002.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.50000 0.50000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}

	{
		map textures/metro/KOsAD_MarcheFace.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro/43707B64ACAFBDD330DC52B518B0DA9E
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro/lm_0002.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}
	{
		map maps/Metro/lm_0002.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.50000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.19531 0.00781
	}

	{
		map textures/metro/KOsAD_MarcheFace.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro/151028D8F81065625FD972A205521343
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro/lm_0002.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}
	{
		map maps/Metro/lm_0002.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}

	{
		map textures/metro/KOsAD_MarcheFace.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro/C209DC75668EEFE81AFDBCADE6C85534
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro/lm_0002.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.50000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.19531 0.00781
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.19531 0.00781
	}

	{
		map textures/metro/KOsAD_MarcheFace.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro/302959BDD1742C48B8EA79F18B54E514
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.00000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.50000
	}

	{
		map textures/metro/KOsAD_MarcheFace.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro/2492ACC389D36A503CDC4C672698A65E
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro/lm_0004.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/Metro/lm_0004.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.00000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.61719 0.00000
	}

	{
		map textures/metro/KOsAD_MarcheTop2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro/9E595210798798B48E014C86DE188A8B
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro/lm_0004.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/Metro/lm_0004.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.00000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.51563 0.00000
	}

	{
		map textures/metro/KOsAD_MarcheTop2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro/9742F3C90EBDF51E994672737E946D0D
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.03125
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.67188 0.05469
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.06250
	}

	{
		map textures/metro/KOsAD_MarcheTop2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro/8A40D8EF7F6A9225AFA594BF8544477B
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.50000
	}
	{
		map maps/Metro/lm_0004.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.00000
	}

	{
		map textures/metro/KOsAD_MarcheTop2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro/0CBA2159B12B63A6F82B2A7773D4C9AF
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro/lm_0004.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.50000 0.50000
	}
	{
		map maps/Metro/lm_0004.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.61719 0.02344
	}

	{
		map textures/metro/KOsAD_MarcheTop2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro/6C49E8450B2C5978E2F2B5513E285E8D
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro/lm_0004.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/Metro/lm_0004.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.50000 0.00000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.03125
	}

	{
		map textures/metro/KOsAD_MarcheTop2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro/2F5F1B8E9947BAE7246FA0716D820C2D
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro/lm_0004.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 -0.50000
	}
	{
		map maps/Metro/lm_0004.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.78906 -0.96094
	}
	{
		map maps/Metro/lm_0004.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.78906 -0.92969
	}

	{
		map textures/metro/KOsAD_MarcheTop2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro/433D3660481956FF2F37CD9FD1DFEC08
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro/lm_0004.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}
	{
		map maps/Metro/lm_0004.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.50000 0.50000
	}

	{
		map textures/metro/KOsAD_MarcheTop2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro/EB60E4DAF98A7BC880A8C72473FC796E
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}
	{
		map maps/Metro/lm_0004.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.00000
	}
	{
		map maps/Metro/lm_0004.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}

	{
		map textures/metro/KOsAD_MarcheTop2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro/9A88835F04F746F4382E8AED5632B406
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro/lm_0004.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.03125
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.06250
	}

	{
		map textures/metro/KOsAD_MarcheTop2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro/3E9B68DCBDCAD21434BC89760591DEB3
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro/lm_0017.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/Metro/lm_0018.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
	}
	{
		map maps/Metro/lm_0018.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.50000 -0.50000
	}

	{
		map textures/metro/sttp13-Extincteur3.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro/4FF414BF368A4F74A701CF60F6C5706C
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro/lm_0006.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/Metro/lm_0007.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
	}
	{
		map maps/Metro/lm_0008.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
	}

	{
		map textures/metro/KOsAD_MetalLampe.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro/E36BEC38C651AEF9897E9DE921D0895F
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro/lm_0005.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/Metro/lm_0006.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
	}
	{
		map maps/Metro/lm_0007.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
	}

	{
		map textures/metro/KOsAD_MetalLampe.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro/B8004F0502B0F6D4CFD128FDCBB0C9DB
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro/lm_0004.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/Metro/lm_0005.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
	}
	{
		map maps/Metro/lm_0006.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
	}

	{
		map textures/metro/KOsAD_MetalLampe.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro/20A7774DC4F91646A29D1816B0AC6C29
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro/lm_0007.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/Metro/lm_0008.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
	}
	{
		map maps/Metro/lm_0005.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}

	{
		map textures/metro/KOsAD_MetalLampe.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro/C4D04532635449420574973433CDDA3A
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro/lm_0005.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/Metro/lm_0006.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
	}
	{
		map maps/Metro/lm_0008.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
	}

	{
		map textures/metro/KOsAD_MetalLampe.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro/0D8597A097C6B113EF6DE7CEC4CD96B3
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro/lm_0007.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/Metro/lm_0008.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}

	{
		map textures/metro/KOsAD_MetalLampe.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro/66E25B87F9E4FCD5E448ABB8BB56D541
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.01563 0.00000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.03125 0.00000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.04688 0.00000
	}

	{
		map textures/metro/KOsAD_MetalLampe.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro/245CF35B820469CCFB97DDC3BFA95167
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro/lm_0008.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/Metro/lm_0008.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 -0.50000
	}
	{
		map maps/Metro/lm_0007.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.20313 -0.09375
	}

	{
		map textures/metro/KOsAD_MetalLampe.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro/A360856DBDDF0C1A7F4F6F0D8E86671A
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro/lm_0008.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/Metro/lm_0008.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 -0.50000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.16406 0.00000
	}

	{
		map textures/metro/KOsAD_MetalLampe.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro/00B3D89E5BA34AE538C72FDD65BF0D54
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro/lm_0004.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/Metro/lm_0007.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
	}
	{
		map maps/Metro/lm_0004.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.00000
	}

	{
		map textures/metro/KOsAD_MetalLampe.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro/A6CB0911807E38E226ABB0872CCA4F90
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/Metro/lm_0006.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
	}
	{
		map maps/Metro/lm_0008.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
	}
	{
		map maps/Metro/lm_0004.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.50000 -0.50000
	}

	{
		map textures/metro/KOsAD_MetalLampe.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro/2E0B955264D77BC2E0EDDB4D4B673C4A
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.06250 0.00000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.14063 0.00000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.16406 0.00000
	}

	{
		map textures/metro/Alumb_t.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro/CF4073A161CEF171B0268FE9EDD4393A
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.50000 0.50000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.02344 0.00000
	}

	{
		map textures/metro/Alumb_t.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro/32F9907514B1C03EEA11A3C2AC67E8E2
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.02344 0.00000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.07031 0.00000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.09375 0.00000
	}

	{
		map textures/metro/Alumb_t.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro/AD9E2467094334495E0C5E7640F154E7
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.50000 0.50000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.01563 0.00000
	}

	{
		map textures/metro/Alumb_t.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro/A5F7170280817FEBB86C3E49B70B6F6E
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.00000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.50000
	}

	{
		map textures/metro/Alumb_t.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro/0393E929FE0C2B8B98FAD4D684667DE4
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.02344 0.00000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.04688 0.00000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.16406 0.00000
	}

	{
		map textures/metro/Alumb_t.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro/A1CE429B4715EFA9B4FA1FFE1D75C25C
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.50000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.08594 0.00000
	}

	{
		map textures/metro/Alumb_t.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro/223F43D27F269C1274B1CA8EC80DD20B
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.50000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.02344 0.00000
	}

	{
		map textures/metro/Alumb_t.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro/80901D8B5DCB7EC1DD60DA9FBAB30CF3
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.02344 0.00000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.04688 0.00000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.07031 0.00000
	}

	{
		map textures/metro/Alumb_t.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro/3B72269A992825BB57378766F1E52296
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.50000 0.50000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.11719 0.00000
	}

	{
		map textures/metro/Alumb_t.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro/A99915ED9302FB4ABF4ACD68B2E352AB
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.50000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.20313 0.00000
	}

	{
		map textures/metro/Alumb_t.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro/5FFD47D70E89051665EA1D3CBD5AB9A8
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.50000 0.50000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.95313 0.00781
	}

	{
		map textures/metro/Alumb_t.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro/8661D3E9FDA9112017377C4356CF61FA
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.12500
	}
	{
		map maps/Metro/lm_0011.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
	}
	{
		map maps/Metro/lm_0012.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
	}

	{
		map textures/metro/navily-ns_bleu.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro/66371673AE0CD690398F728FBA39CB21
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.11719
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.23438
	}

	{
		map textures/metro/navily-ns_bleu.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro/119D8941621210025F55A746A40A7B3A
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.11719
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.23437
	}

	{
		map textures/metro/navily-ns_bleu.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro/9CF42D6358A8BFC30B763F5E0CCB1024
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.12500
	}
	{
		map maps/Metro/lm_0011.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
	}
	{
		map maps/Metro/lm_0012.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
	}

	{
		map textures/metro/RFSP-STEX5b.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

Metro/2F496655C5C341BAEF028E5E3B5513B7
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .5 0 .8 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave triangle 0 .6 .3 .8 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.11719
	}
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square 0 .5 .4 .6 // style 4
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.23438
	}

	{
		map textures/metro/RFSP-STEX5b.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

